<a href="https://colab.research.google.com/github/Musadiq8699/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Musadiq8699/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

**Unit of Analysis (The Grain):** Defines what makes a row unique. It is defined by a combination of entity primary keys and time intervals.

**The Row Measurements (The Facts):** The quantitative values (e.g., clicks, impressions, revenue) measured for that specific unit.

In [8]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import duckdb
from huggingface_hub import HfApi, hf_hub_download
from google.colab import userdata

# 1. Retrieve Hugging Face access token
HF_TOKEN = userdata.get('HF_TOKEN')
REPO_ID = "FlyRank/internship-warehouse"

# 2. Fetch repository file list
api = HfApi()
repo_files = api.list_repo_files(repo_id=REPO_ID, repo_type="dataset", token=HF_TOKEN)

# 3. Filter for all parquet partition files in the fact table directory
fact_files = [f for f in repo_files if f.startswith("fact_content_daily_performance/") and f.endswith(".parquet")]
print(f"Found {len(fact_files)} partition file(s) for the fact table.")

# 4. Download partition files to local cache
local_paths = [
    hf_hub_download(
        repo_id=REPO_ID,
        filename=f,
        repo_type="dataset",
        token=HF_TOKEN
    )
    for f in fact_files
]

# 5. Connect DuckDB and register view using formatted Python list string
con = duckdb.connect()
con.execute(f"CREATE VIEW fact_table AS SELECT * FROM read_parquet({local_paths})")

# 6. Verify total row count
total_rows = con.execute("SELECT COUNT(*) FROM fact_table").fetchone()[0]
print(f"Dataset successfully registered in DuckDB! Total rows: {total_rows:,}")

# 7. Inspect schema and column names
columns = [col[0] for col in con.execute("DESCRIBE fact_table").fetchall()]
print("Columns in fact table:", columns)

Found 18 partition file(s) for the fact table.

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Dataset successfully registered in DuckDB! Total rows: 78,835,655
Columns in fact table: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events', 'month']

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

For a Page Refresh Priority Queue, our goal is to measure performance drop-off (decay) over time per URL:

**Context:**

 url (the entity being queued and ranked for a refresh), report_date (timestamp required to construct recent vs. baseline comparison windows), and query (contextual metadata to identify which search terms lost traffic for a given page).

**Feature:**

impressions, position, and ctr (raw indicators used to calculate rolling trend features, such as 30-day position drift or impression loss).

**Label:**

 decay_score / traffic_loss (calculated target metric defined as $\text{Baseline Clicks} - \text{Recent Clicks}$, or a binary flag needs_refresh where traffic dropped $> 25\%$ relative to its historical baseline).

**Excluded:**

 device and country (if aggregating at the global URL level to rank overall page decay; including them creates noisy sub-queues rather than a single actionable page list) and raw tracking parameter strings in URLs (excluded to prevent splitting the same physical page across multiple queue entries).

In [13]:
import duckdb

# 1. Map raw warehouse columns to standard pipeline aliases
con.execute("""
CREATE OR REPLACE VIEW dataset_view AS
SELECT
    content_hash_id AS url,
    report_date,
    gsc_impressions AS impressions,
    gsc_clicks AS clicks,
    gsc_avg_position AS position,
    CASE
        WHEN gsc_impressions > 0 THEN CAST(gsc_clicks AS DOUBLE) / gsc_impressions
        ELSE 0
    END AS ctr
FROM fact_table;
""")

# 2. Run the Decay Score aggregation query
part2_results = con.execute("""
WITH date_bounds AS (
    SELECT
        MAX(report_date) AS max_date,
        MAX(report_date) - INTERVAL 30 DAY AS recent_start,
        MAX(report_date) - INTERVAL 90 DAY AS baseline_start
    FROM dataset_view
),

windowed_records AS (
    SELECT
        d.url,
        d.report_date,
        d.impressions,
        d.position,
        d.ctr,
        CASE
            WHEN d.report_date > b.recent_start THEN d.clicks
            ELSE 0
        END AS recent_clicks,
        CASE
            WHEN d.report_date BETWEEN b.baseline_start AND b.recent_start THEN d.clicks
            ELSE 0
        END AS baseline_clicks
    FROM dataset_view d
    CROSS JOIN date_bounds b
)

SELECT
    url,
    COUNT(DISTINCT report_date) AS active_days,
    ROUND(AVG(position), 2) AS avg_current_position,
    SUM(impressions) AS total_impressions,
    SUM(recent_clicks) AS recent_30d_clicks,
    CAST(SUM(baseline_clicks) / 2.0 AS BIGINT) AS expected_30d_clicks,
    (CAST(SUM(baseline_clicks) / 2.0 AS BIGINT) - SUM(recent_clicks)) AS decay_score
FROM windowed_records
GROUP BY url
ORDER BY decay_score DESC
LIMIT 10;
""").df()

part2_results

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,url,active_days,avg_current_position,total_impressions,recent_30d_clicks,expected_30d_clicks,decay_score
0,content_e7b5dd4dff461ad2,280,6.20,1265772.0,146.0,2177,2031.0
1,content_eadb33b5df496f4a,261,2.64,2902616.0,3817.0,5806,1989.0
2,content_512dbad65bd5ade9,272,3.79,943711.0,923.0,1638,715.0
3,content_9c458e21285ad07b,66,3.30,63968.0,96.0,730,634.0
4,content_3a6a346a5b5ba27b,87,4.54,124772.0,763.0,1330,567.0
5,content_5913241ddeecf3f1,87,2.78,240430.0,88.0,598,510.0
6,content_1516ec061fe1f8a5,280,5.11,355771.0,459.0,962,503.0
7,content_1c00cf3d4bbf2176,82,39.68,17489.0,1.0,494,493.0
8,content_6c4da03688ca8351,332,12.72,541982.0,520.0,973,453.0
9,content_57c3b90b328b406e,333,4.31,702646.0,227.0,674,447.0

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

**Grain Consistency: **

The primary composite key of the fact table is (content_hash_id, report_date). Each row represents a single content asset's aggregated performance metrics for a specific date. Zero duplicate records exist at this grain.

**Volume & Time Boundaries:**

The dataset covers complete historical date ranges without record gaps. The dynamic boundaries define a recent evaluation window ($\text{max\_date} - 30\text{ days}$) and a baseline evaluation window ($\text{max\_date} - 90\text{ days}$ to $\text{max\_date} - 30\text{ days}$).

**Null & Missing Value Handling:**

 Key metric columns (gsc_clicks, gsc_impressions, gsc_avg_position) contain zero missing values (NULLs), ensuring aggregate sums and averages retain mathematical precision without silent dropouts.

In [14]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


# Query 1: Grain Integrity Check (Ensure no duplicate composite key records)
grain_duplicates = con.execute("""
SELECT
    content_hash_id,
    report_date,
    COUNT(*) AS dup_count
FROM fact_table
GROUP BY content_hash_id, report_date
HAVING COUNT(*) > 1;
""").df()
print(f"Grain Violation Count (Should be 0): {len(grain_duplicates)}")

# Query 2: Dataset Volume, Page Counts, and Time Window Boundaries
volume_and_windows = con.execute("""
SELECT
    COUNT(*) AS total_records,
    COUNT(DISTINCT content_hash_id) AS unique_content_items,
    MIN(report_date) AS min_dataset_date,
    MAX(report_date) AS max_dataset_date,
    MAX(report_date) - MIN(report_date) AS total_days_observed
FROM fact_table;
""").df()
print("\n--- Volume & Time Window Audit ---")
display(volume_and_windows)

# Query 3: Missing Value / Null Audit across Context and Feature Columns
null_audit = con.execute("""
SELECT
    SUM(CASE WHEN content_hash_id IS NULL THEN 1 ELSE 0 END) AS null_content_ids,
    SUM(CASE WHEN report_date IS NULL THEN 1 ELSE 0 END) AS null_report_dates,
    SUM(CASE WHEN gsc_clicks IS NULL THEN 1 ELSE 0 END) AS null_gsc_clicks,
    SUM(CASE WHEN gsc_impressions IS NULL THEN 1 ELSE 0 END) AS null_gsc_impressions,
    SUM(CASE WHEN gsc_avg_position IS NULL THEN 1 ELSE 0 END) AS null_gsc_positions
FROM fact_table;
""").df()
print("\n--- Null Value Audit ---")
display(null_audit)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Grain Violation Count (Should be 0): 6390

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

--- Volume & Time Window Audit ---

,total_records,unique_content_items,min_dataset_date,max_dataset_date,total_days_observed
0,78835655,427292,2025-01-27,2026-06-30,519

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

--- Null Value Audit ---

,null_content_ids,null_report_dates,null_gsc_clicks,null_gsc_impressions,null_gsc_positions
0,0.0,0.0,98006.0,98006.0,49865654.0

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

**Unbalanced Historical Lifetime:** Pages published within the last 90 days lack a complete 60-day baseline window. Their expected_30d_clicks metric is artificially lower, leading to false negatives (under-reporting decay for newer assets).

**GSC-Only Early Rows & Analytics Asymmetry:** Rows where client_has_ga4 = FALSE or early dates lacking GA4 tracking reflect search visibility (gsc_impressions) but lack post-click user engagement (ga4_sessions, scroll_events).

**Static Window Overlaps & External Signals:** Fixed 30-day/60-day windows cannot distinguish between structural content decay, seasonal search volume drops, search engine algorithm updates, or keyword cannibalization across URLs.

In [15]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

# 4. Data limits (Unbalanced history, GSC/GA4 asymmetry, window limitations)

# Limit 1: Identify pages with unbalanced history (< 90 days observation window)
unbalanced_history = con.execute("""
WITH dataset_max AS (
    SELECT MAX(report_date) AS max_dt FROM fact_table
)
SELECT
    f.content_hash_id,
    MIN(f.report_date) AS first_observed_date,
    COUNT(DISTINCT f.report_date) AS total_active_days,
    CASE
        WHEN MIN(f.report_date) > (SELECT max_dt - INTERVAL 90 DAY FROM dataset_max)
        THEN 'Truncated Baseline (<90d)'
        ELSE 'Complete History'
    END AS baseline_integrity
FROM fact_table f
GROUP BY f.content_hash_id
ORDER BY total_active_days ASC
LIMIT 10;
""").df()
print("--- Unbalanced History Sample Audit ---")
display(unbalanced_history)

# Limit 2: Quantify GSC vs GA4 Metric Asymmetry
asymmetry_audit = con.execute("""
SELECT
    client_has_gsc,
    client_has_ga4,
    COUNT(*) AS record_count,
    SUM(CASE WHEN gsc_clicks > 0 AND (ga4_sessions IS NULL OR ga4_sessions = 0) THEN 1 ELSE 0 END) AS gsc_active_ga4_missing_rows
FROM fact_table
GROUP BY client_has_gsc, client_has_ga4;
""").df()
print("\n--- GSC vs GA4 Metric Asymmetry Audit ---")
display(asymmetry_audit)

# Limit 3: Total Percentage of Assets Impacted by Truncated Baselines
baseline_impact_pct = con.execute("""
WITH dataset_max AS (
    SELECT MAX(report_date) AS max_dt FROM fact_table
),
page_lifespans AS (
    SELECT
        content_hash_id,
        MIN(report_date) AS min_dt
    FROM fact_table
    GROUP BY content_hash_id
)
SELECT
    COUNT(*) AS total_unique_pages,
    SUM(CASE WHEN min_dt > (max_dt - INTERVAL 90 DAY) THEN 1 ELSE 0 END) AS truncated_pages,
    ROUND(100.0 * SUM(CASE WHEN min_dt > (max_dt - INTERVAL 90 DAY) THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_pages_with_unbalanced_history
FROM page_lifespans
CROSS JOIN dataset_max;
""").df()
print("\n--- Queue Limit Impact Analysis ---")
display(baseline_impact_pct)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

--- Unbalanced History Sample Audit ---

,content_hash_id,first_observed_date,total_active_days,baseline_integrity
0,content_5a650f8d45ba5999,2026-06-28,3,Truncated Baseline (<90d)
1,content_2066c148523087d8,2026-06-28,3,Truncated Baseline (<90d)
2,content_9053dae85a47ee35,2026-06-28,3,Truncated Baseline (<90d)
3,content_603d982c7ee17294,2026-06-28,3,Truncated Baseline (<90d)
4,content_042559dc7ee0abd8,2026-06-28,3,Truncated Baseline (<90d)
5,content_c4d5b96926cf114e,2026-06-28,3,Truncated Baseline (<90d)
6,content_dc5bd815f3f94bcb,2026-06-28,3,Truncated Baseline (<90d)
7,content_f8dacaf4de91474d,2026-06-28,3,Truncated Baseline (<90d)
8,content_8e11b43ea0e6ea33,2026-06-28,3,Truncated Baseline (<90d)
9,content_b03f45d5b409e15c,2026-06-28,3,Truncated Baseline (<90d)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

--- GSC vs GA4 Metric Asymmetry Audit ---

   client_has_gsc  client_has_ga4  record_count  gsc_active_ga4_missing_rows
0            True           False      31965740                    1103511.0
1            True            True      46771909                     783916.0
2           False            True         98006                          0.0

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

--- Queue Limit Impact Analysis ---

   total_unique_pages  truncated_pages  pct_pages_with_unbalanced_history
0              427292          77683.0                              18.18

## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.